//TODO 영화, 시리즈, 오리지널 배너

export const mainBanner = [
  {
    id: 0,
    title: '주토피아',
    background_img: '/images/main/mainBanner1.png',
    poster_path: '/fZcab1yiKXsjx3S8D4KRHZsnMGC.jpg',
    logo: '/public/images/main/mainBannerLogo1.png',
    age: 'All',
    release_date: '2020',
    running_time: '1시간 40분',
    genres: ['애니메이션,', '모험,', '기족,', 'SF,', '판타지,', '코미디'],
    type: 'movie',
  },
  {
    id: 1,
    title: '더 베어',
    background_img: '/images/main/mainBanner2.png',
    poster_path: '/t23nESlKRH1qQYWIoUQCOWkS2dl.jpg',
    logo: '/public/images/main/mainBannerLogo2.png',
    age: '15',
    release_date: '2022~2025',
    total_series: '총 4개의 시즌',
    genres: ['드라마,', '코미디'],
    type: 'tv',
  },
  {
    id: 2,
    title: '북극성',
    background_img: '',
    poster_path: '',
    logo: '',
    age: '15',
    release_date: '2025',
    total_series: '총 1개의 시즌',
    genres: ['첩보/스파이,', '스릴러'],
    type: 'tv',
  },

  {
    id: 3,
    title: '라푼젤 미니스토리',
    background_img: '/images/kidsMain/kidsBanner2.png',
    logo: '/images/kidsMain/kidsBannerLogo2.png',
    logo_size: 'small',
    age: 'All',
    release_date: '2017',
    total_series: '총 1개의 시즌',
    gernes: ['어드밴쳐,', '액션', '코미디'],
    type: 'tv',
  },
];
